### ISSUE TITLE
Stable tag

### ISSUE THREAD

**Issue by NiR-** [jonathan-sousa/silex-amqp-provider#4]
Hi, 

If this provider is production-ready, can you create a stable tag ? If this is not, can you update the README.md.

Thanks.

**Comment by wysow** [comment]
Please also consider updating the version of this dependency https://github.com/videlalvaro/php-amqplib if it's not obviously breaking your code ;)

**Comment by jonathan-sousa** [comment]
Done.
Thx for your feedback !
